name: Deploy to GitHub Pages

on:
  push:
    tags:
      - v[0-9]+.*
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Install Pre-requisites
        run: just install

      - name: Build syntax diagrams and book
        run: just build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'book'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
